"""FGASGASGA

Revision ID: cadab2b6d0a0
Revises: 0d0ffe625d27
Create Date: 2025-02-09 18:07:19.503060

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cadab2b6d0a0"
down_revision = None  # или другая актуальная миграция

branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
